import { NextRequest, NextResponse } from "next/server";
import { createPromptVideoJob } from "@/lib/jobs/repository";
import { triggerJobProcessing } from "@/lib/jobs/trigger";
import { enforceRateLimit } from "@/lib/security/rate-limit";
import { getRequestIp } from "@/lib/security/request-ip";
import { logger } from "@/lib/logging/logger";

export const runtime = "nodejs";

const RATE_LIMIT_RULES = [
  { name: "random_video_per_day", windowSec: 86_400, limit: 5 },
] as const;

export async function POST(request: NextRequest) {
  try {
    const ip = getRequestIp(request);

    const rateLimit = await enforceRateLimit({
      scope: "api_video_random",
      key: ip,
      rules: [...RATE_LIMIT_RULES],
    });

    if (!rateLimit.allowed) {
      return NextResponse.json(
        {
          error: "Rate limit exceeded. You have reached your daily limit for random videos.",
          retryAfterSec: rateLimit.retryAfterSec,
        },
        { status: 429 },
      );
    }

    const job = await createPromptVideoJob({
      requestKind: "generic_cinema",
      packageType: "60s",
      subjectName: "Random Generation",
      subjectDescription: "Random TikTok-style 9:16 video generated by AI.",
      audioEnabled: true,
      visibility: "public",
      pricingMode: "public",
      experience: "hyperm",
      paymentWaived: true,
    });

    await triggerJobProcessing(job.jobId);

    logger.info("random_video_queued", {
      component: "api",
      route: "/api/video/random",
      jobId: job.jobId,
      ip,
    });

    return NextResponse.json({
      jobId: job.jobId,
      status: "pending",
    });
  } catch (error) {
    logger.error("random_video_failed", {
      component: "api",
      errorCode: "random_video_failed",
      errorMessage: error instanceof Error ? error.message : "Unknown error",
    });

    return NextResponse.json(
      { error: "Failed to generate random video" },
      { status: 500 },
    );
  }
}
