// MoltBook publisher - posts to AI social network
import { getDb } from "@/lib/firebase/admin";
import { getEnv } from "@/lib/env";
import { getJobArtifacts, listCompletedJobArtifacts } from "@/lib/jobs/repository";
import { logger } from "@/lib/logging/logger";
import { JobDocument, ReportDocument, VideoDocument } from "@/lib/types/domain";

// Agent claim status on MoltBook
type MoltBookAgentStatus = "pending_claim" | "claimed" | "suspended";
// Publication tracking states
type MoltBookPublicationStatus = "pending" | "posting" | "posted" | "pending_verification" | "failed";

// Stale posting timeout - 5 minutes
const POSTING_STALE_MS = 5 * 60_000;

// Get MoltBook API base URL from env
function getMoltBookBaseUrl(): string {
  const env = getEnv();
  return (env.MOLTBOOK_API_BASE_URL || "https://www.moltbook.com/api/v1").replace(/\/+$/, "");
}

// ISO timestamp helper
function nowIso(): string {
  return new Date().toISOString();
}

// Firestore collection for publication tracking
function moltBookPublicationCollection() {
  return getDb().collection("moltbook_publications");
}

// Firestore collection for agent credentials
function moltBookAgentStateCollection() {
  return getDb().collection("moltbook_agent_state");
}

// Normalize raw publication doc data
function normalizePublication(
  jobId: string,
  raw?: Partial<MoltBookPublicationDocument> | null,
): MoltBookPublicationDocument {
  return {
    jobId,
    status:
      raw?.status === "posting" || raw?.status === "posted" || raw?.status === "failed" || raw?.status === "pending_verification"
        ? raw.status
        : "pending",
    attempts: Math.max(0, Math.floor(raw?.attempts ?? 0)),
    createdAt: raw?.createdAt ?? nowIso(),
    updatedAt: raw?.updatedAt ?? nowIso(),
    lastAttemptAt: raw?.lastAttemptAt ?? null,
    postedAt: raw?.postedAt ?? null,
    moltBookPostId: raw?.moltBookPostId ?? null,
    moltBookPostUrl: raw?.moltBookPostUrl ?? null,
    errorMessage: raw?.errorMessage ?? null,
  };
}

// Publication tracking document schema
interface MoltBookPublicationDocument {
  jobId: string;
  status: MoltBookPublicationStatus;
  attempts: number;
  createdAt: string;
  updatedAt: string;
  lastAttemptAt: string | null;
  postedAt: string | null;
  moltBookPostId: string | null;
  moltBookPostUrl: string | null;
  errorMessage: string | null;
  verificationChallenge?: string | null;
  verificationExpiresAt?: string | null;
}

// MoltBook API registration response
interface MoltBookAgentRegistration {
  agent_id: string;
  name: string;
  status: MoltBookAgentStatus;
  api_key: string;
  claim_url: string;
  verification_code: string;
  registered_at: string;
}

// MoltBook post API response
interface MoltBookPostPayload {
  post_id?: string;
  url?: string;
  verification_required?: boolean;
  verification_challenge?: string;
  expires_at?: string;
  status?: "posted" | "pending_verification";
}

// Sync summary for batch operations
export interface MoltBookSyncSummary {
  scanned: number;
  posted: number;
  skipped: number;
  failed: number;
  claimUrl?: string;
  agentStatus?: MoltBookAgentStatus;
  results: Array<{
    jobId: string;
    status: "posted" | "skipped" | "failed";
    reason?: string;
    postId?: string | null;
    postUrl?: string | null;
  }>;
}

function shortWallet(wallet: string): string {
  if (!wallet) return "unknown";
  if (wallet.length <= 12) return wallet;
  return `${wallet.slice(0, 4)}...${wallet.slice(-4)}`;
}

function clamp(text: string, maxLength: number): string {
  if (text.length <= maxLength) {
    return text;
  }
  return `${text.slice(0, Math.max(0, maxLength - 3)).trim()}...`;
}

/**
 * Build post title and content for a completed video
 */
function buildPostContent(input: {
  job: JobDocument;
  report: ReportDocument | null;
  video: VideoDocument | null;
}): { title: string; content: string; submolt: string } {
  const env = getEnv();
  const walletLabel = shortWallet(input.job.wallet);
  const personality = input.report?.walletPersonality || input.report?.styleClassification || "AI Cinema";
  const summary = clamp(
    input.report?.summary || input.report?.narrativeSummary || "Fresh AI-generated autobiographical video.",
    2000,
  );
  const jobUrl = new URL(`/job/${input.job.jobId}`, env.APP_BASE_URL).toString();

  return {
    title: `New MythX Drop: ${walletLabel}`,
    content: [
      `🎬 **${personality}**`,
      "",
      summary,
      "",
      `**Watch the full video:** ${jobUrl}`,
      "",
      "---",
      `*Generated by MythX on ${new Date().toLocaleDateString()}*`,
      "",
      `#MythX #AICinema #AutobiographicalVideo`,
    ].join("\n"),
    submolt: "general",
  };
}

/**
 * Claim publication for atomic posting (prevents duplicates)
 */
async function claimPublication(jobId: string): Promise<MoltBookPublicationDocument | null> {
  return getDb().runTransaction(async (tx) => {
    const ref = moltBookPublicationCollection().doc(jobId);
    const snap = await tx.get(ref);
    const current = normalizePublication(
      jobId,
      snap.exists ? ((snap.data() as Partial<MoltBookPublicationDocument>) ?? null) : null,
    );

    if (current.status === "posted") {
      return null;
    }

    const lastAttemptAtMs = current.lastAttemptAt ? Date.parse(current.lastAttemptAt) : 0;
    const isFreshPosting =
      current.status === "posting" &&
      Number.isFinite(lastAttemptAtMs) &&
      Date.now() - lastAttemptAtMs < POSTING_STALE_MS;

    if (isFreshPosting) {
      return null;
    }

    const updated: MoltBookPublicationDocument = {
      ...current,
      status: "posting",
      attempts: current.attempts + 1,
      updatedAt: nowIso(),
      lastAttemptAt: nowIso(),
      errorMessage: null,
    };

    tx.set(ref, updated, { merge: true });
    return updated;
  });
}

async function markPublicationPosted(input: { 
  jobId: string; 
  postId?: string | null;
  postUrl?: string | null;
}) {
  const timestamp = nowIso();
  await moltBookPublicationCollection().doc(input.jobId).set(
    {
      jobId: input.jobId,
      status: "posted",
      updatedAt: timestamp,
      postedAt: timestamp,
      moltBookPostId: input.postId ?? null,
      moltBookPostUrl: input.postUrl ?? null,
      errorMessage: null,
    } satisfies Partial<MoltBookPublicationDocument>,
    { merge: true },
  );
}

async function markPublicationPendingVerification(input: { 
  jobId: string; 
  postId?: string | null;
  challenge: string | null;
  expiresAt: string | null;
}) {
  const timestamp = nowIso();
  await moltBookPublicationCollection().doc(input.jobId).set(
    {
      jobId: input.jobId,
      status: "pending_verification",
      updatedAt: timestamp,
      moltBookPostId: input.postId ?? null,
      moltBookPostUrl: null,
      verificationChallenge: input.challenge,
      verificationExpiresAt: input.expiresAt,
      errorMessage: null,
    } satisfies Partial<MoltBookPublicationDocument>,
    { merge: true },
  );
}

async function markPublicationFailed(input: { jobId: string; errorMessage: string }) {
  await moltBookPublicationCollection().doc(input.jobId).set(
    {
      jobId: input.jobId,
      status: "failed",
      updatedAt: nowIso(),
      errorMessage: input.errorMessage,
    } satisfies Partial<MoltBookPublicationDocument>,
    { merge: true },
  );
}

/**
 * Register agent with MoltBook
 */
export async function registerMoltBookAgent(input: {
  name: string;
  description: string;
}): Promise<MoltBookAgentRegistration> {
  const response = await fetch(`${getMoltBookBaseUrl()}/agents/register`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ name: input.name, description: input.description }),
  });

  const result = await response.json();
  if (!result.success) {
    throw new Error(`MoltBook registration failed: ${result.error || response.status}`);
  }

  const data = result.data as MoltBookAgentRegistration;

  await moltBookAgentStateCollection().doc("mythxmythx").set(
    {
      agentId: data.agent_id,
      name: data.name,
      status: data.status,
      apiKey: data.api_key,
      claimUrl: data.claim_url,
      verificationCode: data.verification_code,
      registeredAt: data.registered_at,
      updatedAt: nowIso(),
    },
    { merge: true },
  );

  logger.info("moltbook_agent_registered", {
    component: "moltbook_publisher",
    agentId: data.agent_id,
    name: data.name,
    status: data.status,
    claimUrl: data.claim_url,
  });

  return data;
}

/**
 * Get stored agent credentials from Firestore
 */
async function getStoredAgentCredentials(): Promise<{
  apiKey: string;
  agentId: string;
  status: MoltBookAgentStatus;
  claimUrl: string | null;
} | null> {
  const doc = await moltBookAgentStateCollection().doc("mythxmythx").get();
  if (!doc.exists) return null;

  const data = doc.data();
  if (!data?.apiKey) return null;

  return {
    apiKey: data.apiKey,
    agentId: data.agentId || "unknown",
    status: data.status || "pending_claim",
    claimUrl: data.claimUrl || null,
  };
}

/**
 * Resolve API key (env var > Firestore > register new)
 */
async function resolveApiKey(): Promise<{
  apiKey: string;
  agentId: string;
  status: MoltBookAgentStatus;
  claimUrl: string | null;
}> {
  const env = getEnv();

  if (env.MOLTBOOK_AGENT_API_KEY) {
    return { apiKey: env.MOLTBOOK_AGENT_API_KEY, agentId: "mythxmythx", status: "claimed", claimUrl: null };
  }

  const stored = await getStoredAgentCredentials();
  if (stored) return stored;

  const registration = await registerMoltBookAgent({
    name: "MythX",
    description: "AI cinematic storyteller that transforms X profiles into autobiographical videos. Powered by MythX.",
  });

  return {
    apiKey: registration.api_key,
    agentId: registration.agent_id,
    status: registration.status,
    claimUrl: registration.claim_url,
  };
}

/**
 * Post to MoltBook with verification challenge handling
 */
async function postToMoltBook(input: {
  apiKey: string;
  title: string;
  content: string;
  submolt: string;
}): Promise<{ 
  postId: string | null; 
  postUrl: string | null; 
  status: "posted" | "pending_verification";
  verificationChallenge: string | null;
  verificationExpiresAt: string | null;
}> {
  const postResponse = await fetch(`${getMoltBookBaseUrl()}/posts`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${input.apiKey}`,
    },
    body: JSON.stringify({
      submolt_name: input.submolt,
      title: input.title,
      content: input.content,
      type: "text",
    }),
  });

  const postResult = await postResponse.json();
  if (!postResult.success) {
    throw new Error(`MoltBook post creation failed: ${postResult.error || postResponse.status}`);
  }

  const postData = postResult.data as MoltBookPostPayload;

  if (postData.verification_required && postData.verification_challenge) {
    logger.warn("moltbook_verification_required", {
      component: "moltbook_publisher",
      postId: postData.post_id,
      challenge: postData.verification_challenge,
      expiresAt: postData.expires_at,
    });

    return {
      postId: postData.post_id || null,
      postUrl: null,
      status: "pending_verification",
      verificationChallenge: postData.verification_challenge,
      verificationExpiresAt: postData.expires_at || null,
    };
  }

  return {
    postId: postData.post_id || null,
    postUrl: postData.url || null,
    status: "posted",
    verificationChallenge: null,
    verificationExpiresAt: null,
  };
}

/**
 * Publish a completed job to MoltBook
 */
export async function publishCompletedJobToMoltBook(jobId: string): Promise<{
  jobId: string;
  status: "posted" | "skipped" | "failed";
  reason?: string;
  postId?: string | null;
  postUrl?: string | null;
  claimUrl?: string | null;
}> {
  const claim = await claimPublication(jobId);
  if (!claim) {
    return { jobId, status: "skipped", reason: "already_posted_or_in_progress" };
  }

  try {
    const credential = await resolveApiKey();

    if (credential.status === "pending_claim" && credential.claimUrl) {
      logger.warn("moltbook_agent_not_claimed", {
        component: "moltbook_publisher",
        jobId,
        claimUrl: credential.claimUrl,
      });
      return { jobId, status: "skipped", reason: "agent_pending_claim", claimUrl: credential.claimUrl };
    }

    const { job, report, video } = await getJobArtifacts(jobId);
    if (!job || job.status !== "complete") {
      throw new Error("Job is not ready for MoltBook publication.");
    }

    const { title, content, submolt } = buildPostContent({ job, report, video });
    const result = await postToMoltBook({ apiKey: credential.apiKey, title, content, submolt });

    if (result.status === "pending_verification") {
      await markPublicationPendingVerification({
        jobId,
        postId: result.postId,
        challenge: result.verificationChallenge,
        expiresAt: result.verificationExpiresAt,
      });

      logger.warn("moltbook_post_pending_verification", {
        component: "moltbook_publisher",
        jobId,
        postId: result.postId,
      });

      return {
        jobId,
        status: "failed",
        reason: "pending_verification",
        postId: result.postId,
        postUrl: null,
      };
    }

    await markPublicationPosted({ jobId, postId: result.postId, postUrl: result.postUrl });

    return { jobId, status: "posted", postId: result.postId, postUrl: result.postUrl };
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown MoltBook error";
    await markPublicationFailed({ jobId, errorMessage: message });

    logger.warn("moltbook_publication_failed", {
      component: "moltbook_publisher",
      stage: "publish_completed_job",
      jobId,
      errorCode: "moltbook_publication_failed",
      errorMessage: message,
    });

    return { jobId, status: "failed", reason: message };
  }
}

/**
 * Sync entire gallery to MoltBook
 */
export async function syncGalleryToMoltBook(requestedLimit?: number): Promise<MoltBookSyncSummary> {
  const limit = Math.max(1, Math.min(50, requestedLimit && Number.isFinite(requestedLimit)
    ? Math.floor(requestedLimit) : 12));

  const galleryItems = await listCompletedJobArtifacts(limit);
  const results: MoltBookSyncSummary["results"] = [];

  let claimUrl: string | null = null;
  let agentStatus: MoltBookAgentStatus = "claimed";

  try {
    const credential = await resolveApiKey();
    claimUrl = credential.claimUrl;
    agentStatus = credential.status;
  } catch {
    // Will fail on first post
  }

  for (const item of galleryItems) {
    const result = await publishCompletedJobToMoltBook(item.job.jobId);
    results.push({
      jobId: item.job.jobId,
      status: result.status,
      reason: result.reason,
      postId: result.postId,
      postUrl: result.postUrl,
    });
  }

  return {
    scanned: galleryItems.length,
    posted: results.filter((item) => item.status === "posted").length,
    skipped: results.filter((item) => item.status === "skipped").length,
    failed: results.filter((item) => item.status === "failed").length,
    claimUrl: claimUrl || undefined,
    agentStatus,
    results,
  };
}

/**
 * Get agent registration status and claim link
 */
export async function getMoltBookAgentStatus(): Promise<{
  registered: boolean;
  status: MoltBookAgentStatus | null;
  claimUrl: string | null;
  agentId: string | null;
}> {
  const stored = await getStoredAgentCredentials();
  if (!stored) {
    return { registered: false, status: null, claimUrl: null, agentId: null };
  }

  return {
    registered: true,
    status: stored.status,
    claimUrl: stored.claimUrl,
    agentId: stored.agentId,
  };
}
